# ==============================================================================
# CAMERA INTRINSICS CONFIGURATION
# ==============================================================================

cam_0:
  width: 1032
  height: 772
  fx: 864.387610
  fy: 863.858468
  cx: 519.731844
  cy: 385.718642
  distortion_model: "pinhole"
  distortion_coefficients: [-0.185152, 0.219182, 0.0, 0.0, 0.0]

cam_1:
  width: 1032
  height: 772
  fx: 867.051573
  fy: 866.739349
  cx: 520.459460
  cy: 384.232118
  distortion_model: "pinhole"
  distortion_coefficients: [-0.187918, 0.222345, 0.0, 0.0, 0.0]
