# ==============================================================================
# MAIN CONFIGURATION FOR cuVSLAM RUNNER
# ==============================================================================

# Mode of operation: mono, stereo, inertial, rgbd, etc.
mode: "stereo"

# Enabled/disabled SLAM mode
use_slam: true

# Enable/disable Rerun visualization
verbose: true

# ------------------------------------------------------------------------------
# Active Bag Path and Topic Configuration
# ------------------------------------------------------------------------------
bag_path: "/mnt/foundation_ssd/foundation_data/recorded_data/bags/VSLAM/Botanic_garden/1018_00_VLIO.bag"
gt_bag_path: /mnt/foundation_ssd/foundation_data/recorded_data/bags/VSLAM/Botanic_garden/gt_1018_00_qnew.bag
use_realsense_bag: false

topics:
  left: /dalsa_gray/left/image_raw
  right: /dalsa_gray/right/image_raw
