# ====================================================
# main configuration for cuVSLAM runner
# ====================================================

mode: "stereo"  # Mode: mono, stereo, inertial, rgbd
use_slam: true  # on/off SLAM mode
verbose: true   # on/off Rerun

# Odometry settings
use_denoising: true
use_motion_model: true
max_frame_delta_s: 0.5
rectified_stereo_camera: false
multicam_mode: "precision" # precision, moderate, performance
async_sba: true
debug_imu_mode: false

# SLAM settings
max_map_size: 0
map_cell_size: 0.1
max_landmarks_distance: 10.0
planar_constraints: false
sync_mode: false
throttling_time_ms: 0

# Custom tracking and optimization parameters
num_desired_tracks: 1000
ransac_filter: false
num_sba_frames: 16
num_fixed_sba_frames: 7
num_sba_iterations: 16
pnp_max_iterations: 16

# ====================================================
# bag path and topic configuration
# ====================================================

bag_path: "/mnt/foundation_ssd/foundation_data/recorded_data/bags/VSLAM/MADMAX/A1_20181202-153722.bag"
gt_bag_path:
use_realsense_bag: false

topics:
  left: /hcru2/pt_stereo_rect/left/image
  right: /hcru2/pt_stereo_rect/right/image
  gt: /tf
  gt_frame_id: nav_current_submap
  gt_child_frame_id: imu
